 version: 2.1
 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1-jammy
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install chrome
      - run:
          name: "Run visual tests"
          command: npm test
